const { Router } = require('express')
const authRoutes = require('./auth')
const turismRoutes = require('./turism')
const petRoutes = require('./pets')
const courseRoutes = require('./courses')
const propertyRoutes = require('./properties')
const dishRoutes = require('./dishes')
const planRoutes = require('./plans')
const modalityRoutes = require('./modalities')
const eventRoutes = require('./events')
const adminRoutes = require('./admin')

const router = Router()

router.use('/auth', authRoutes)
router.use('/turism', turismRoutes)
router.use('/pets', petRoutes)
router.use('/courses', courseRoutes)
router.use('/properties', propertyRoutes)
router.use('/dishes', dishRoutes)
router.use('/plans', planRoutes)
router.use('/modalities', modalityRoutes)
router.use('/events', eventRoutes)
router.use('/admin', adminRoutes)

module.exports = router
