const { Router } = require('express')
const authRoutes = require('./auth')
const turismRoutes = require('./turism')
const petRoutes = require('./pets')
const courseRoutes = require('./courses')
const propertyRoutes = require('./properties')
const dishRoutes = require('./dishes')
const planRoutes = require('./plans')
const modalityRoutes = require('./modalities')
const eventRoutes = require('./events')
const adminRoutes = require('./admin')

const modaRoutes = require('./modaRoutes')
const streamingRoutes = require('./streamingRoutes')
const receitasRoutes = require('./receitasRoutes')
const eventosProjRoutes = require('./eventosRoutes')
const hardwareRoutes = require('./hardwareRoutes')
const artigosRoutes = require('./artigosRoutes')

// Projetos novos (spec) — cada arquivo agrupa os recursos do projeto.
const dentroDoJogoRoutes = require('./dentroDoJogo.routes')
const pitocosCarRoutes = require('./pitocosCar.routes')
const lumiereRoutes = require('./lumiere.routes')
const nexusRoutes = require('./nexus.routes')
const maxblockRoutes = require('./maxblock.routes')
const swellPointRoutes = require('./swellPoint.routes')

const router = Router()

router.use('/auth', authRoutes)
router.use('/turism', turismRoutes)
router.use('/pets', petRoutes)
router.use('/courses', courseRoutes)
router.use('/properties', propertyRoutes)
router.use('/dishes', dishRoutes)
router.use('/plans', planRoutes)
router.use('/modalities', modalityRoutes)
router.use('/events', eventRoutes)
router.use('/admin', adminRoutes)

router.use('/moda', modaRoutes)
router.use('/streaming', streamingRoutes)
router.use('/receitas', receitasRoutes)
router.use('/projetos-eventos', eventosProjRoutes)
router.use('/hardware', hardwareRoutes)
router.use('/artigos', artigosRoutes)

router.use('/dentro-do-jogo', dentroDoJogoRoutes)
router.use('/pitocos-car', pitocosCarRoutes)
router.use('/lumiere', lumiereRoutes)
router.use('/nexus', nexusRoutes)
router.use('/maxblock', maxblockRoutes)
router.use('/swell-point', swellPointRoutes)

module.exports = router
